FROM gcr.io/google_containers/kubernetes-apiserver-amd64:latest   
FROM gcr.io/google_containers/kube-scheduler-amd64:latest
FROM gcr.io/google_containers/kube-proxy-amd64:latest
FROM gcr.io/google_containers/kube-controller-manager-amd64:latest
FROM gcr.io/google_containers/etcd-amd64:latest
FROM gcr.io/google_containers/k8s-dns-sidecar-amd64:latest
FROM gcr.io/google_containers/k8s-dns-kube-dns-amd64:latest
FROM gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:latest
FROM gcr.io/google_containers/pause-amd64:latest



MAINTAINER yu
