#FROM gcr.io/google_containers/kube-apiserver-amd64:v1.9.0   
#FROM gcr.io/google_containers/kube-scheduler-amd64:v1.9.0
#FROM gcr.io/google_containers/kube-proxy-amd64:v1.9.0
#FROM gcr.io/google_containers/kube-controller-manager-amd64:v1.9.0
#FROM gcr.io/google_containers/etcd-amd64:3.1.10
FROM gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.7
#FROM gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
#FROM gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.7
#FROM gcr.io/google_containers/pause-amd64:3.0 

MAINTAINER yu
